### ISSUE TITLE
Make it possible to run scalafix with the same scala binary version as the target

### ISSUE THREAD

**Issue by bjaglin** [cosmicsilence/gradle-scalafix#32]
This is necessary for advanced rules using the presentation compiler such as `ExplicitResultTypes` to work.

See
* https://github.com/scalacenter/scalafix/issues/1111
* https://github.com/scalacenter/scalafix/pull/1152/files#diff-8f1370021f0c21599d22a292e6ee5a9446f05c18a05f5c3bb250dea3884c72eeR86
* https://github.com/scalacenter/sbt-scalafix/pull/121

**Comment by marcelocenerine** [comment]
@bjaglin  the Gradle plugin used to use the `scalafix-interfaces` jar and dynamically load Scalafix via a custom classloader. But for some reason I scratched that and started using the `scalafix-cli` jar instead: https://github.com/cosmicsilence/gradle-scalafix/pull/18/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7L19 . IIRC we were running into OOM issues in our integration tests due to scalafix + scala and all transitive dependencies being loaded multiple times via different classloader instances (on the same JVM). I will try to revisit that during my time off in the upcoming weeks. 

Thanks for the pointers 👍 . It looks like `Scalafix.fetchAndClassloadInstance` simplifies things a lot.

**Comment by bjaglin** [comment]
Thanks for working on that! I see you kept classloading on the plugin side - no luck with caching `Scalafix.fetchAndClassloadInstance`?
