### ISSUE TITLE
Failure to download semantic db for scala 2.13.5

### ISSUE THREAD

**Issue by moonkev** [cosmicsilence/gradle-scalafix#40]
Hello

Just as in #23 and #34 there is an issue downloading semanticdb-scalac for scala 2.13.5, as only version 4.4.10 is available right now for scala 2.13.5.  I wonder, is it viable to allow the user to specify a specific semanticdb-scalac version via the scalafix {} gradle configuration?

**Comment by marcelocenerine** [comment]
It sounds reasonable to me, especially because the Sbt plugin seems to allow that via `semanticdbVersion`. Ideally users should rely on the version set by the Gradle plugin, but it can be used as a temporary workaround until a new version of the Gradle plugin is released every time a new version of Scala/Semanticdb comes out.
