### ISSUE TITLE
Avoid conditionally registering task doFirst action

### ISSUE THREAD

**Issue by DanielThomas** [cosmicsilence/gradle-scalafix#58]
We've noticed the `io.github.cosmicsilence.scalafix.ScalafixPlugin$_configureTaskForSourceSet_closure4$_closure11` `doFirst` action being added conditionally in our Scala builds using this plugin.

https://github.com/cosmicsilence/gradle-scalafix/blob/531a9b665c03df2d68e9594ebb30ad81fcde5fb7/src/main/groovy/io/github/cosmicsilence/scalafix/ScalafixPlugin.groovy#L84-L91

Per Gradle's documentation, the `doFirst` action should always be added and the conditional logic be included inside, otherwise when the property varies it changes the input fingerprint for the task:

https://docs.gradle.org/current/userguide/common_caching_problems.html#custom_actions

**Comment by aishfenton** [comment]
Just for background context. I think the reason it's like this, is that the logic was forcing a dependency resolve. Which becomes super annoying if all you're doing is running something like `./gradlew tasks`. So ideally needs to find way to achieve both (no dependency resolve, and having a conditional doFirst).

**Comment by aishfenton** [comment]
Just for context. Think the reason it was changed to this, was partially to resolve https://github.com/cosmicsilence/gradle-scalafix/issues/49 . But then again ... hopefully you can have both a non-conditional `doFirst`, but still only execute the logic within it, on task execution.

**Comment by DanielThomas** [comment]
It can be conditional, you just need to always add the `doFirst`:
```
if (extension.semanticdb.autoConfigure.get()) { 
    scalafixTask.dependsOn sourceSet.compileTask 
}
sourceSet.compileTask.doFirst { 
    if (extension.semanticdb.autoConfigure.get()) { 
        configureSemanticdbCompilerPlugin(project, sourceSet, extension) 
    }
} 
```

Custom `doFirst` actions aren't ideal because they couple the buildscript classpath to the inputs for the task so it causes task to be considered dirty for an incremental build and for the build cache to miss. Using the task configuration avoidance APIs is often what you actually want:

https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

**Comment by aishfenton** [comment]
Another potential issue I just spotted (but related to above) is that these lines 

```scala
def compilerOpts = [
  '-Xplugin:' + configuration.asPath,
  '-P:semanticdb:sourceroot:' + project.projectDir,
  '-Yrangepos'
]
sourceSet.addCompilerOptions(compilerOpts)
```

Are going to bust the cache keys. As the absolute paths used will be different on different machines/environments. The first path you can get around by removing `-Xplugin` and instead using [this](https://docs.gradle.org/current/userguide/scala_plugin.html#sec:scala_compiler_plugins). Have tried that on my local environment and seems to work well for the plugin. The second path one however (`sourceroot`) I'm still trying to figure out a workaround for.

**Comment by marcelocenerine** [comment]
Caching is not something we've spent enough time on, so I'm sure there is room for improvements there.

@aishfenton could you share more detail on the issue you described regarding absolute paths on different machines/environments? (e.g. a real use case) The reason we chose not to use `scalaCompilerPlugins` is that it became available as an incubating feature only in Gradle 6.4.

**Comment by aishfenton** [comment]
👍. So real-life situation for us is that we build our project on our local machines (where folks may have checked out to different places) and we have a CI cloud build that we don't have much control over. This means that the absolute paths to the Jar / sourceroot will be different on each machine. 

Unfortunately since these absolute paths are compiler options, that cause Gradle to have different cache keys, for the compile task, on different machines. Which means we're not able to take advantage of cross-machine caching. Currently we rely on that quite heavily to keep our build to reasonable runtime lengths (with no cache, it can take ~40mins, from cache, even if it has to download the class artifacts, can be ~30s). 

The `scalaCompilerPlugins` gets around the first problem because Gradle will normalize the paths to be cache friendly. The `sourceroot` however I'm still struggling to find a solution for.

**Comment by marcelocenerine** [comment]
@aishfenton thanks for sharing more details on your use case. It makes sense to me now.

We could update the Scalafix plugin to leverage `scalaCompilerPlugins` if it is running on Gradle +6.4 and fallback to the current non-cache-friendly approach if running on older versions. I need to check, but I suspect that the mechanism for loading custom Scalafix rules could also suffer from the same issue. However, this would only be worth the effort if we can find a solution for `sourceroot` as well. I'd need to do some testing and dig into the semanticdb source code to better understand how that parameter is used internally.

**Comment by aishfenton** [comment]
@DanielThomas and I have been digging into the `sourceroot` and it looks like it's treated as being either an absolute path, or relative to the CWD. Unfortunately in Gradle the CWD _isn't_ the project root, instead each worker has it's own CWD. 

We also found that `semaneticdb` checks to make sure that whatever file `scalac` is compiling, can also be found on the `sourceroot` path. And skips producing the semanticdb file where that isn't true :/ (which explains why this not being set correctly results in no semanticdb files being created at all). See [here](https://github.com/scalameta/scalameta/blob/main/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala#L59
).

I think the best solution to this is for semanticdb to have an option to setting the `sourceroot` relative to the targetroot. Created an issue here on scalameta. 

https://github.com/scalameta/scalameta/issues/2515

**Comment by marcelocenerine** [comment]
@aishfenton / @DanielThomas given that some compiler options are conditionally added based on the `scalafix.semanticdb.autoConfigure` property, wouldn't the input fingerprint for the compiler task change anyway?

**Comment by aishfenton** [comment]
@marcelocenerine yes that's correct. In practice it ends up being more opaque than that. Because `check` depends on `checkScalaFix`, and `build -> check -> checkScalafix`. So what ends up happening is that often you end up with 
non-cacheable compiler results, and to most users it's totally opaque and mysterious as to why. 

One solution could be to just isolate `checkScalaFix`, so that none of the Gradle lifecycle tasks depend on it. At least that way you know that if you're run `checkScalaFix` explicitly, it's supposed to break caching. 

Fwiw, I didn't actually notice much of a performance hit by just always including the `semanticdb` plugin. But I guess it's all relative.

**Comment by aishfenton** [comment]
I think for our use case (and probably many others), we're likely opt in to always having semanticdb added, and just taking the hit. Because we need it for IDE tooling (bloop, metals, etc) anyway.
